version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/legstrong

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
